export const MEJS_PLAYER_INITIALIZED = 'MEJS_PLAYER_INITIALIZED';
export const MEJS_SWAP = 'MEJS_SWAP';
export const MEJS_CAPTIONS = 'MEJS_CAPTIONS';
export const MEJS_PLAYING = 'MEJS_PLAYING';
export const MEJS_RELOAD = 'MEJS_RELOAD';
export const MEJS_CANVAS_INDEX = 'MEJS_CANVAS_INDEX';

export const NAV_ITEM_CLICK = 'NAV_ITEM_CLICK';
export const NAV_STARTTIME = 'NAV_STARTTIME';
export const NAV_UNCLICK = 'NAV_UNCLICK';

export const FETCH_MANIFEST_REQUEST = 'FETCH_MANIFEST_REQUEST';
export const FETCH_MANIFEST_SUCCESS = 'FETCH_MANIFEST_SUCCESS';
export const FETCH_MANIFEST_FAILURE = 'FETCH_MANIFEST_FAILURE';

export const UPDATE_EXTERNAL_CONFIG = 'UPDATE_EXTERNAL_CONFIG';
