export const MEJS_PLAYER_INITIALIZED = 'MEJS_PLAYER_INITIALIZED';
export const MEJS_CAPTIONS = 'MEJS_CAPTIONS';
export const MEJS_PLAYING = 'MEJS_PLAYING';
export const MEJS_SWITCH_CANVAS = 'MEJS_SWITCH_CANVAS';

export const NAV_ITEM_CLICK = 'NAV_ITEM_CLICK';
export const NAV_START_TIME = 'NAV_START_TIME';
export const NAV_RESET_CLICK = 'NAV_RESET_CLICK';

export const FETCH_MANIFEST_REQUEST = 'FETCH_MANIFEST_REQUEST';
export const FETCH_MANIFEST_SUCCESS = 'FETCH_MANIFEST_SUCCESS';
export const FETCH_MANIFEST_FAILURE = 'FETCH_MANIFEST_FAILURE';

export const UPDATE_EXTERNAL_CONFIG = 'UPDATE_EXTERNAL_CONFIG';
