orbs:
  node: circleci/node@2.0
version: 2.1
workflows:
  test-matrix:
    jobs:
      - node/test:
          version: 13.12.0
          pkg-manager: yarn
      - node/test:
          version: 12.16.1
          pkg-manager: yarn
      - node/test:
          version: 10.19.0
          pkg-manager: yarn
