orbs:
  node: circleci/node@2.0
version: 2.1
jobs:
  test:
    executor:
      name: node/default
      tag: << parameters.version >>
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-key: yarn.lock
      - run:
          command: yarn test
workflows:
  test-matrix:
    jobs:
      - test:
          version: 13.12.0
      - test:
          version: 12.16.1
      - test:
          version: 10.19.0
